site_name: کهربا زبان برنامه نویسی ساده و قدرتمند
theme:
  name: material
  direction: rtl
  language: fa
  logo: assets/images/logo.png

  features:
    - header.autohide

extra_css:
  - stylesheets/extra.css
