site_name: زبان برنامه نویسی کهربا
plugins:
  - search:
      lang: "fa"
theme:
  name: material
  direction: rtl
  language: fa
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: UA-XXXXXXXX-X

  version:
    provider: mike

repo_url: https://github.com/kahroba-lang/kahroba
repo_name: ریپوزیتوری گیت‌هاب
