site_name: زبان برنامه نویسی کهربا
nav:
  - پیشگفتار: about.md
  - شروع:
      - نصب و استفاده: construction/install.md
      - سلام دنیا: sample/hello-world.md

  - مفاهیم زبان کهربا:
      - کامنت‌ها: concepts/comment.md
      - متغیرها |‌ Variables: concepts/define.md
      - آرایه‌ها | Arrays: concepts/arrays.md
      - مپ‌ | Map: concepts/map.md
      - عبارت‌های منطقی | boolean: concepts/boolean.md
plugins:
  - search
theme:
  name: material
  direction: rtl
  language: fa
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico

  features:
    - content.code.annotate
    - navigation.instant
    - navigation.expand

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: UA-XXXXXXXX-X

  version:
    provider: mike

repo_url: https://github.com/kahroba-lang/docs
repo_name: ریپوزیتوری گیت‌هاب
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
